AllCops:
  TargetRubyVersion: 2.1

Style/AccessModifierIndentation:
  EnforcedStyle: outdent

Documentation:
  Enabled: false

Metrics/LineLength:
  Max: 160

Style/StringLiterals:
  EnforcedStyle: double_quotes

Style/DoubleNegation:
  Enabled: false

Style/ParallelAssignment:
  Enabled: false

Metrics/ClassLength:
  Enabled: false
